name: ly_cocoapods_visualtool
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.1
  desktop_drop: ^0.4.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - script/
